# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 674d95cd2646d2e73dfce94619fcc3df7beaa6a7c3976288782311f4e0161040338990cf2e1c4952b73c7f3067e1c924fe476ca8f87b45bd600da245ada16982

test:
  secret_key_base: 008b09673521a21b0038321f93e93ace8d3b898209d2b064694f15270728583c898e7e3bacc3f9284c8d3a36e225fb52395cecd71ed1e47838abd496e1b913d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
